import { StyleSheet } from 'react-native';

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ecf0f1',
    paddingVertical: 20,
  },
  header: {
    backgroundColor: 'darkgreen',
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    zIndex: 1,
  },
  headerText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
    flex: 1,
    textAlign: 'center',
  },
  listContainer: {
    alignItems: 'flex-start',
    marginHorizontal: '25%',
  },
  hamburgerButton: {
    position: 'absolute',
    left: 16,
    zIndex: 2,
  },
  hamburgerIcon: {
    fontSize: 24,
    color: 'white',
  },
  section: {
    padding: 10,
    justifyContent: 'center',
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: 'grey',
    marginHorizontal: 10,
    marginVertical: 10,
  },
  heading: {
    fontWeight: 'bold',
    fontSize: 22,
    textAlign: 'center',
    marginVertical: 10,
  },
  subheading: {
    fontSize: 20,
    textAlign: 'center',
    marginHorizontal: '1%',
  },
  closeButton: {
    alignSelf: 'flex-start',
    marginBottom: 20,
    marginTop: 40,
  },
  closeButtonText: {
    color: 'white',
    fontSize: 24,
  },
  menuItem: {
    color: 'white',
    fontSize: 18,
    marginBottom: 15,
  },
  paragraph: {
    margin: 24,
    fontSize: 17,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  squareContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginVertical: 10,
  },
  square: {
    width: 100,
    height: 120,
    borderWidth: 2,
    borderColor: 'blue',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  squareText: {
    color: 'blue',
    fontWeight: 'bold',
    fontSize: 35,
  },
  squareText1: {
    color: 'grey',
    fontSize: 15,
  },
  label: {
    position: 'absolute',
    bottom: -1,
    left: 0,
    right: 0,
    height: 20,
    backgroundColor: 'blue',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  labelText: {
    color: 'white',
    fontSize: 14,
  },
  button: {
    backgroundColor: '#ccc',
    paddingHorizontal: 15,
    paddingVertical: 10,
    marginHorizontal: 5,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  button1: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    height: '20%',
    backgroundColor: 'lightgreen',
    justifyContent: 'center',
    alignItems: 'center',
  },
  button2: {
    borderColor: 'black',
    borderWidth: 1,
    width: '75%',
    height: 40,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
    marginHorizontal: '15%',
    padding: 5,
  },
  button3Text: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  button3: {
    borderWidth: 1,
    borderColor: 'black', // Fixed from 'border'
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 10,
    marginVertical: 10,
    marginBottom: 10,
    backgroundColor: 'blue',
  },
  button4: {
    borderColor: 'black',
    borderWidth: 1,
    borderRadius: 8,
    width: '50%',
    marginHorizontal: '25%',
    paddingVertical: 10,
    backgroundColor: 'white',
  },
  disabledButton: {
    backgroundColor: 'gray',
  },
  okButton: {
    padding: 10,
    backgroundColor: 'blue',
    borderRadius: 5,
  },
  okButtonText: {
    color: 'white',
    fontSize: 18,
  },
  selectedButton: {
    backgroundColor: 'lightgrey',
    borderWidth: 1,
    borderColor: 'blue', // Fixed from 'border'
  },
  input: {
    marginTop: 25,
    height: 45,
    width: '60%',
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    fontSize: 16,
    marginBottom: 20,
    backgroundColor: '#fff',
    textAlign: 'center',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  progressBar: {
    height: 5,
    width: '100%',
    backgroundColor: '#e0e0e0',
    borderRadius: 2.5,
    overflow: 'hidden',
    marginBottom: 20,
  },
  progress: {
    height: '100%',
    backgroundColor: 'blue',
    borderRadius: 2.5,
  },
  dropdown: {
    width: '84%',
    height: 65,
    fontSize: 20,
    borderColor: 'black',
    borderWidth: 1,
    borderRadius: 8,
    borderBottomEndRadius: 0,
    borderBottomStartRadius: 0,
    backgroundColor: '#f9f9f9',
    marginTop: 10,
    marginBottom: 15,
    justifyContent: 'center',
    marginHorizontal: 'auto',
  },
  modalBackground: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: 300,
    padding: 20,
    backgroundColor: 'white',
    borderRadius: 10,
    alignItems: 'center',
  },
  modalHeading: {
    fontSize: 24,
    fontWeight: 'bold',
    color: 'blue',
    marginBottom: 10,
  },
  modalText: {
    fontSize: 18,
    marginBottom: 20,
    textAlign: 'center',
  },
});